# Generated by Django 4.0.3 on 2022-07-16 13:15

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('school', models.CharField(max_length=100, unique=True)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=10)),
                ('account_bank', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_no', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('matric_no', models.CharField(max_length=20)),
                ('program', models.CharField(max_length=30)),
            ],
        ),
    ]
