# Generated by Django 4.0.3 on 2022-07-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_student_has_paid_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='images/person-circle.svg', null=True, upload_to='images/'),
        ),
    ]
