# Generated by Django 4.0.3 on 2022-07-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_authuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='images/person-circle.svg', upload_to='images/'),
        ),
    ]
