# Generated by Django 4.0.3 on 2022-08-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_studentlogbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminuser',
            old_name='amount',
            new_name='it_amount',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='siwes_amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pendingpayment',
            name='payment_type',
            field=models.CharField(default='Siwes Payment', max_length=20),
            preserve_default=False,
        ),
    ]
