# Generated by Django 4.0.3 on 2022-08-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_amount_adminuser_it_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingpayment',
            name='payment_type',
            field=models.CharField(max_length=25),
        ),
    ]
