# Generated by Django 4.0.3 on 2022-08-06 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_pendingpayment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingpayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
