# Generated by Django 4.0.3 on 2022-08-06 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_pendingpayment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pendingpayment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='pendingpayment',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
